permalink: /:categories/:title/

title: London’s response to the coronavirus pandemic (COVID-19)
email: hello@wearefuturegov.com
description: This is a website about our response to the coronavirus pandemic. Here you can see all our work.
baseurl: ""
url: "" # the base hostname & protocol for your site, e.g. http://example.com

plugins:
  - jekyll-feed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "default"