permalink: /:categories/:title/

title: Local response to coronavirus (COVID-19)
email: hello@wearefuturegov.com
description: We're building a team from local government, community groups and voluntary services for collective actionto address shared problems during an emergency unlike any other.
baseurl: ""
url: "" # the base hostname & protocol for your site, e.g. http://example.com

plugins:
  - jekyll-feed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
